#%RAML 1.0 Library
types:
  Item: !include item.raml
  PagedCollectionResponsetype: !include pagedCollectionResponsetype.raml
  FormDataSample: !include formDataSample.raml
  CustomerRequestData: !include ..//exchange_modules/2b9166a0-49cb-4a32-a6eb-f177d1e0cb9e/generic-api-datatypes/1.0.0/generic-api-datatypes.raml